# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.IntegerField(default=-1)),
                ('longitute', models.IntegerField(default=181)),
                ('noaa', models.FloatField(default=-460)),
                ('weather_com', models.FloatField(default=-460)),
                ('accuweather', models.FloatField(default=-460)),
            ],
        ),
    ]
