# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0002_temperature_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Average',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_temperature', models.FloatField(default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='temperature',
            name='name',
            field=models.CharField(default='City Name', max_length=100),
        ),
        migrations.AddField(
            model_name='average',
            name='temperature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.Temperature'),
        ),
    ]
