# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0003_auto_20171002_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='average',
            old_name='temperature',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='name',
            new_name='city',
        ),
    ]
