# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0004_auto_20171002_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='accuweather',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='latitude',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='longitute',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='noaa',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='weather_com',
            field=models.FloatField(default=None, null=True),
        ),
    ]
